version: "3.8"
services:
  db:
    container_name: "cshare-database"
    build:
      context: .
      target: database
    restart: always
    ports:
      - "5432:5432"
  backend:
    container_name: "cshare-server"
    build:
      context: .
      target: server
    ports:
      - "5675:5675"
volumes:
  postgres_data:
    driver: local


# Add Networking in docker-compose.yml  to enable communication between containers.
# Also update setting models/models.go with the correct IP address of the database and database with server.
