# Build a go docker container and add ports to it for communication.
version: '3'
services:
  server:
    build:
      context: ./
      target: production
    ports:
      - 5675:5675
    restart: on-failure
    depends_on:
      - postgres-db
    networks:
      - fullstack

  postgres-db:
    build:
      context: ./
      target: database
    container_name: full_db_postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
    restart: unless-stopped

volumes:
  database_postgres:


networks:
  fullstack:
    driver: bridge
