name: Binary and container release

on:
  push:
    branches: [main]
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.5"
          cache: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Docker container push
      - uses: actions/checkout@v2
      - name: docker-login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: build
        run: |
          docker build -t cshare-db --target=database .
          docker build -t cshare-server --target=production .
      - name: docker push
        run: |
          docker push jammutkarsh/cshare-server
